ALTER TABLE "advertisement_settings"
  ADD COLUMN IF NOT EXISTS "promo_enabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "promo_label" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "promo_discount_type" VARCHAR(20) NOT NULL DEFAULT 'PERCENT',
  ADD COLUMN IF NOT EXISTS "promo_discount_value" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "promo_starts_at" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "promo_ends_at" TIMESTAMP(3);
